### ISSUE TITLE
`rollup` import map processed improperly

### ISSUE THREAD

**Issue by manuel3108** [unplugin/unplugin-isolated-decl#34]
### Describe the bug

Using the reproduction below, run `pnpm install` and `pnpm build`
Bevor diving in, let's have a look at the input map provided to `rollup`:
```js
// https://github.com/manuel3108/unplugin-isolated-decl-repro/blob/master/rollup.config.js#L12-L16

/** @type {RollupOptions["input"]} */
let inputs = {
    index: `${projectRoot}/index.ts`,
    bar: `${projectRoot}/foo/bar/index.ts`,
};
```

The `bar.d.ts` is located in `dist/bar.d.ts` but references the import `baz` in `./baz`. This is incorrect, it should actually be `./foo/bar/baz`.

This was introduced by [`0.6.6`](https://github.com/unplugin/unplugin-isolated-decl/releases/tag/v0.6.6) as `0.6.5` is working perfectly. I'm assuming that this was this commit: https://github.com/unplugin/unplugin-isolated-decl/commit/c724430

In `0.6.5` `dist/bar.d.ts` was actually located in `./dist/foo/bar/index.d.ts` which made the problem mentioned above go away. 

### Reproduction

https://github.com/manuel3108/unplugin-isolated-decl-repro

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 4.12 GB / 15.93 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.0 - ~\AppData\Roaming\npm\pnpm.CMD
    bun: 1.1.22 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.98)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Should be fixed in the latest commit.

**Comment by manuel3108** [comment]
@sxzz very close, but still not fully there 😆. If you are importing your files with a `.ts` extension, then the path rewriting does not work as expected. Sorry for providing an incomplete example in the first place.

Here is my updated sample: https://github.com/manuel3108/unplugin-isolated-decl-repro/commit/962cd2bafa3c8dda8370addaa9993069c2ee312e

**Comment by sxzz** [comment]
Try 0.8.1

**Comment by sxzz** [comment]
Glad to see Svelte is already using it! Feel free to reach out if you have any issues with the plugin.
